name: spice_ecommerce_pwa
description: "AI-driven e-commerce PWA for Indonesian spice farmers connecting with buyers"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0

  # State Management
  provider: ^6.1.2
  flutter_riverpod: ^2.4.9

  # Network & API
  http: ^1.1.2
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3

  # Authentication & Security
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.2
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  geolocator: ^10.1.0

  # Forms & Validation
  form_validator: ^2.1.1
  email_validator: ^2.1.17

  # Charts & Analytics
  fl_chart: ^0.66.2

  # PWA & Web
  flutter_web_plugins:
    sdk: flutter

  # Notifications & Background
  flutter_local_notifications: ^17.0.0
  workmanager: ^0.5.2

  # Payment
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1

  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/spices/

  # Fonts - Using Google Fonts CDN (loaded in web/index.html)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf

  # Flutter Web configuration - moved to separate files
  # PWA configuration will be in web/manifest.json
  # Service worker configuration will be in web/sw.js
